name: 'Deploy Web App to GitHub Pages'
author: 'Dimitri Baptiste'
description: 'Render the web app using Node.js Remix package, then deploy the generated folder to GitHub Pages'
branding:
  icon: 'upload-cloud'
  color: 'red'
  
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
          
      - name: Install dependencies
        run: npm install
        shell: bash

      - name: Build App
        run: npx remix vite:build
        shell: bash

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
